package com.cognizant.jpaas2.api.domain;
// Generated Jan 15, 2013 1:14:03 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * AppEnvMaster generated by hbm2java
 */
public class AppEnvMaster implements java.io.Serializable {

	private Long id;
	private long version;
	private String shortDesc;
	private String longDesc;
	private Integer providerId;
	private Integer cloudAccountId;
	private String blueprintFileId;
	private String deploymentFileId;
	private Set<AppEnvInstance> appEnvInstances = new HashSet<AppEnvInstance>(0);

	public String getBlueprintFileId() {
		return blueprintFileId;
	}

	public void setBlueprintFileId(String blueprintFileId) {
		this.blueprintFileId = blueprintFileId;
	}
	
		
	public String getDeploymentFileId() {
		return deploymentFileId;
	}

	public void setDeploymentFileId(String deploymentFileId) {
		this.deploymentFileId = deploymentFileId;
	}



	private Set<AppEnvParams> appEnvParamses = new HashSet<AppEnvParams>(0);

	public AppEnvMaster() {
	}

	public AppEnvMaster(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public AppEnvMaster(String shortDesc, String longDesc, Integer providerId, Integer cloudAccountId, Set<AppEnvInstance> appEnvInstances, Set<AppEnvParams> appEnvParamses) {
		this.shortDesc = shortDesc;
		this.longDesc = longDesc;
		this.providerId = providerId;
		this.cloudAccountId = cloudAccountId;
		this.appEnvInstances = appEnvInstances;
		this.appEnvParamses = appEnvParamses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public String getLongDesc() {
		return this.longDesc;
	}

	public void setLongDesc(String longDesc) {
		this.longDesc = longDesc;
	}

	public Integer getProviderId() {
		return this.providerId;
	}

	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	public Integer getCloudAccountId() {
		return this.cloudAccountId;
	}

	public void setCloudAccountId(Integer cloudAccountId) {
		this.cloudAccountId = cloudAccountId;
	}

	public Set<AppEnvInstance> getAppEnvInstances() {
		return this.appEnvInstances;
	}

	public void setAppEnvInstances(Set<AppEnvInstance> appEnvInstances) {
		this.appEnvInstances = appEnvInstances;
	}

	public Set<AppEnvParams> getAppEnvParamses() {
		return this.appEnvParamses;
	}

	public void setAppEnvParamses(Set<AppEnvParams> appEnvParamses) {
		this.appEnvParamses = appEnvParamses;
	}
}
