package com.cognizant.jpaas2.api.domain;
// Generated Jan 15, 2013 1:14:03 PM by Hibernate Tools 3.2.1.GA

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 * AppEnvTaskOverview generated by hbm2java
 */
public class AppEnvTaskOverview implements java.io.Serializable, Comparable<AppEnvTaskOverview> {

	private Long id;
	private AppEnvInstance appEnvInstance;
	private String shortDesc;
	private String longDesc;
	private Long category;

	public AppEnvTaskOverview() {
	}

	public AppEnvTaskOverview(AppEnvInstance appEnvInstance, String shortDesc) {
		this.appEnvInstance = appEnvInstance;
		this.shortDesc = shortDesc;
	}

	public AppEnvTaskOverview(AppEnvInstance appEnvInstance, String shortDesc, String longDesc, Long category) {
		this.appEnvInstance = appEnvInstance;
		this.shortDesc = shortDesc;
		this.longDesc = longDesc;
		this.category = category;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public AppEnvInstance getAppEnvInstance() {
		return this.appEnvInstance;
	}

	public void setAppEnvInstance(AppEnvInstance appEnvInstance) {
		this.appEnvInstance = appEnvInstance;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public String getLongDesc() {
		return this.longDesc;
	}

	public void setLongDesc(String longDesc) {
		this.longDesc = longDesc;
	}

	public Long getCategory() {
		return category;
	}

	public void setCategory(Long category) {
		this.category = category;
	}

	@Override
	public int hashCode() {
		int hash = 3;
		hash = 17 * hash + (this.id != null ? this.id.hashCode() : 0);
		hash = 17 * hash + (this.appEnvInstance != null ? this.appEnvInstance.hashCode() : 0);
		hash = 17 * hash + (this.shortDesc != null ? this.shortDesc.hashCode() : 0);
		hash = 17 * hash + (this.longDesc != null ? this.longDesc.hashCode() : 0);
		return hash;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final AppEnvTaskOverview other = (AppEnvTaskOverview) obj;
		return true;
	}

	public int compareTo(AppEnvTaskOverview o) {
		return this.getId().compareTo(o.getId());
	}
}
