package com.cognizant.jpaas2.api.domain;
// Generated Jan 15, 2013 1:14:03 PM by Hibernate Tools 3.2.1.GA

/**
 * AppEnvParams generated by hbm2java
 */
public class AppEnvParams implements java.io.Serializable {

	private Long id;
	private AppEnvMaster appEnvMaster;
	private String paramName;
	private String paramValue;

	public AppEnvParams() {
	}

	public AppEnvParams(AppEnvMaster appEnvMaster, String paramName, String paramValue) {
		this.appEnvMaster = appEnvMaster;
		this.paramName = paramName;
		this.paramValue = paramValue;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public AppEnvMaster getAppEnvMaster() {
		return this.appEnvMaster;
	}

	public void setAppEnvMaster(AppEnvMaster appEnvMaster) {
		this.appEnvMaster = appEnvMaster;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}
}
