//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 12:29:59 PM IST 
//
package com.cognizant.formit.entity.infrastructureContext;

import com.cognizant.formit.model.IDeploymentConfig;
import java.util.Iterator;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cloud" type="{http://formation.deployer.jpass.cognizant.com}ICloud"/>
 *         &lt;element name="project" type="{http://formation.deployer.jpass.cognizant.com}IProject"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
	"cloud",
	"project"
})
@XmlRootElement(name = "context")
public class Context implements IDeploymentConfig {

	@XmlElement(required = true)
	protected ICloud cloud;
	@XmlElement(required = true)
	protected IProject project;

	/**
	 * Gets the value of the cloud property.
	 *
	 * @return possible object is {@link ICloud }
	 *
	 */
	public ICloud getCloud() {
		return cloud;
	}

	/**
	 * Sets the value of the cloud property.
	 *
	 * @param value allowed object is {@link ICloud }
	 *
	 */
	public void setCloud(ICloud value) {
		this.cloud = value;
	}

	/**
	 * Gets the value of the project property.
	 *
	 * @return possible object is {@link IProject }
	 *
	 */
	public IProject getProject() {
		return project;
	}

	/**
	 * Sets the value of the project property.
	 *
	 * @param value allowed object is {@link IProject }
	 *
	 */
	public void setProject(IProject value) {
		this.project = value;
	}

	@Override
	public String toString() {
		return "Context{" + "cloud=" + cloud + ", project=" + project + '}';
	}
}
