//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 12:29:59 PM IST 
//
package com.cognizant.formit.entity.infrastructureContext;

import com.cognizant.formit.model.IDeploymentConfig;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ICloud complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ICloud">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accessId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="secretKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="templates">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="template" type="{http://formation.deployer.jpass.cognizant.com}ITemplate"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ICloud", propOrder = {
	"name",
	"providerName",
	"url",
	"accessId",
	"secretKey",
	"virtualMachineServiceURL",
	"keypath",
	"keystorePwd",
	"serviceId",
	"keyPairId",
	"templates"
})
public class ICloud implements IDeploymentConfig {

	@XmlElement(required = true)
	protected String name;
	@XmlElement(required = true)
	protected String providerName;
	@XmlElement(required = true)
	protected String url;
	@XmlElement(required = true)
	protected String accessId;
	@XmlElement(required = true)
	protected String secretKey;
	@XmlElement(required = true)
	protected String virtualMachineServiceURL;
	@XmlElement(required = true)
	protected String keypath;
	@XmlElement(required = true)
	protected String keystorePwd;

	public String getProviderName() {
		return providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	public String getVirtualMachineServiceURL() {
		return virtualMachineServiceURL;
	}

	public void setVirtualMachineServiceURL(String virtualMachineServiceURL) {
		this.virtualMachineServiceURL = virtualMachineServiceURL;
	}

	public String getKeypath() {
		return keypath;
	}

	public void setKeypath(String keypath) {
		this.keypath = keypath;
	}

	public String getKeystorePwd() {
		return keystorePwd;
	}

	public void setKeystorePwd(String keystorePwd) {
		this.keystorePwd = keystorePwd;
	}

	public String getServiceId() {
		return serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public String getKeyPairId() {
		return keyPairId;
	}

	public void setKeyPairId(String keyPairId) {
		this.keyPairId = keyPairId;
	}
	@XmlElement(required = true)
	protected String serviceId;
	@XmlElement(required = true)
	protected String keyPairId;
	@XmlElement(required = true)
	protected ICloud.Templates templates;

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the url property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * Sets the value of the url property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setUrl(String value) {
		this.url = value;
	}

	/**
	 * Gets the value of the accessId property.
	 *
	 */
	public String getAccessId() {
		return accessId;
	}

	/**
	 * Sets the value of the accessId property.
	 *
	 */
	public void setAccessId(String value) {
		this.accessId = value;
	}

	/**
	 * Gets the value of the secretKey property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSecretKey() {
		return secretKey;
	}

	/**
	 * Sets the value of the secretKey property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSecretKey(String value) {
		this.secretKey = value;
	}

	/**
	 * Gets the value of the templates property.
	 *
	 * @return possible object is {@link ICloud.Templates }
	 *
	 */
	public ICloud.Templates getTemplates() {
		return templates;
	}

	/**
	 * Sets the value of the templates property.
	 *
	 * @param value allowed object is {@link ICloud.Templates }
	 *
	 */
	public void setTemplates(ICloud.Templates value) {
		this.templates = value;
	}

	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="template" type="{http://formation.deployer.jpass.cognizant.com}ITemplate"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
		"template"
	})
	public static class Templates {

		@XmlElement(required = true)
		protected ITemplate template;

		/**
		 * Gets the value of the template property.
		 *
		 * @return possible object is {@link ITemplate }
		 *
		 */
		public ITemplate getTemplate() {
			return template;
		}

		/**
		 * Sets the value of the template property.
		 *
		 * @param value allowed object is {@link ITemplate }
		 *
		 */
		public void setTemplate(ITemplate value) {
			this.template = value;
		}
	}

	@Override
	public String toString() {
		return "ICloud{" + "name=" + name + ", url=" + url + ", accessId=" + accessId + ", secretKey=" + secretKey + ", virtualMachineServiceURL=" + virtualMachineServiceURL + ", keypath=" + keypath + ", keystorePwd=" + keystorePwd + ", serviceId=" + serviceId + ", keyPairId=" + keyPairId + ", templates=" + templates + '}';
	}
}
