//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 12:29:59 PM IST 
//
package com.cognizant.formit.entity.infrastructureContext;

import com.cognizant.formit.model.IDeploymentConfig;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for IProject complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="IProject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ssh-keypath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IProject", propOrder = {
	"sshKeypath",
	"name",
	"resource"
})
public class IProject implements IDeploymentConfig {

	@XmlElement(name = "ssh-keypath", required = true)
	protected String sshKeypath;
	@XmlElement(required = true)
	protected String name;
	@XmlElement(required = true)
	protected String resource;

	/**
	 * Gets the value of the sshKeypath property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSshKeypath() {
		return sshKeypath;
	}

	/**
	 * Sets the value of the sshKeypath property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSshKeypath(String value) {
		this.sshKeypath = value;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the resource property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getResource() {
		return resource;
	}

	/**
	 * Sets the value of the resource property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setResource(String value) {
		this.resource = value;
	}

	@Override
	public String toString() {
		return "IProject{" + "sshKeypath=" + sshKeypath + ", name=" + name + ", resource=" + resource + '}';
	}
}
