//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 12:29:59 PM IST 
//
package com.cognizant.formit.entity.infrastructureContext;

import com.cognizant.formit.model.IDeploymentConfig;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ITemplate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ITemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="securityGroups" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remoteFS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sshPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remoteUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rootCommandPrefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subnetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ITemplate", propOrder = {
	"mi",
	"description",
	"zone",
	"securityGroups",
	"remoteFS",
	"sshPort",
	"type",
	"tag",
	"userData",
	"remoteUser",
	"rootCommandPrefix",
	"subnetId",
	"cpuCount",
	"diskSizeInGb",
	"name",
	"productId",
	"ramInMb"
})
public class ITemplate implements IDeploymentConfig {

	@XmlElement(required = true)
	protected String mi;
	@XmlElement(required = true)
	protected String description;
	@XmlElement(required = true)
	protected String zone;
	@XmlElement(required = true)
	protected String securityGroups;
	@XmlElement(required = true)
	protected String remoteFS;
	@XmlElement(required = true)
	protected String sshPort;
	@XmlElement(required = true)
	protected String type;
	@XmlElement(required = true)
	protected String tag;
	@XmlElement(required = true)
	protected String userData;
	@XmlElement(required = true)
	protected String remoteUser;
	@XmlElement(required = true)
	protected String rootCommandPrefix;
	@XmlElement(required = true)
	protected String subnetId;
	@XmlElement(required = true)
	protected String cpuCount;
	@XmlElement(required = true)
	protected String diskSizeInGb;
	@XmlElement(required = true)
	protected String name;
	@XmlElement(required = true)
	protected String productId;

	public String getCpuCount() {
		return cpuCount;
	}

	public void setCpuCount(String cpuCount) {
		this.cpuCount = cpuCount;
	}

	public String getDiskSizeInGb() {
		return diskSizeInGb;
	}

	public void setDiskSizeInGb(String diskSizeInGb) {
		this.diskSizeInGb = diskSizeInGb;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getRamInMb() {
		return ramInMb;
	}

	public void setRamInMb(String ramInMb) {
		this.ramInMb = ramInMb;
	}
	@XmlElement(required = true)
	protected String ramInMb;

	/**
	 * Gets the value of the mi property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getMi() {
		return mi;
	}

	/**
	 * Sets the value of the mi property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setMi(String value) {
		this.mi = value;
	}

	/**
	 * Gets the value of the description property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the zone property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getZone() {
		return zone;
	}

	/**
	 * Sets the value of the zone property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setZone(String value) {
		this.zone = value;
	}

	/**
	 * Gets the value of the securityGroups property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSecurityGroups() {
		return securityGroups;
	}

	/**
	 * Sets the value of the securityGroups property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSecurityGroups(String value) {
		this.securityGroups = value;
	}

	/**
	 * Gets the value of the remoteFS property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getRemoteFS() {
		return remoteFS;
	}

	/**
	 * Sets the value of the remoteFS property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setRemoteFS(String value) {
		this.remoteFS = value;
	}

	/**
	 * Gets the value of the sshPort property.
	 *
	 */
	public String getSshPort() {
		return sshPort;
	}

	/**
	 * Sets the value of the sshPort property.
	 *
	 */
	public void setSshPort(String value) {
		this.sshPort = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the tag property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * Sets the value of the tag property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setTag(String value) {
		this.tag = value;
	}

	/**
	 * Gets the value of the userData property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getUserData() {
		return userData;
	}

	/**
	 * Sets the value of the userData property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setUserData(String value) {
		this.userData = value;
	}

	/**
	 * Gets the value of the remoteUser property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getRemoteUser() {
		return remoteUser;
	}

	/**
	 * Sets the value of the remoteUser property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setRemoteUser(String value) {
		this.remoteUser = value;
	}

	/**
	 * Gets the value of the rootCommandPrefix property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getRootCommandPrefix() {
		return rootCommandPrefix;
	}

	/**
	 * Sets the value of the rootCommandPrefix property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setRootCommandPrefix(String value) {
		this.rootCommandPrefix = value;
	}

	/**
	 * Gets the value of the subnetId property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSubnetId() {
		return subnetId;
	}

	/**
	 * Sets the value of the subnetId property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setSubnetId(String value) {
		this.subnetId = value;
	}

	@Override
	public String toString() {
		return "ITemplate{" + "mi=" + mi + ", description=" + description + ", zone=" + zone + ", securityGroups=" + securityGroups + ", remoteFS=" + remoteFS + ", sshPort=" + sshPort + ", type=" + type + ", tag=" + tag + ", userData=" + userData + ", remoteUser=" + remoteUser + ", rootCommandPrefix=" + rootCommandPrefix + ", subnetId=" + subnetId + ", cpuCount=" + cpuCount + ", diskSizeInGb=" + diskSizeInGb + ", name=" + name + ", productId=" + productId + ", ramInMb=" + ramInMb + '}';
	}
}
