//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 12:29:59 PM IST 
//
package com.cognizant.formit.entity.infrastructureContext;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.cognizant.formit.entity.environmentprofile package. <p>An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes
 * representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory implements BaseObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * com.cognizant.formit.entity.environmentprofile
	 *
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link ICloud.Templates }
	 *
	 */
	public ICloud.Templates createICloudTemplates() {
		return new ICloud.Templates();
	}

	/**
	 * Create an instance of {@link Context }
	 *
	 */
	public Context createContext() {
		return new Context();
	}

	/**
	 * Create an instance of {@link ITemplate }
	 *
	 */
	public ITemplate createITemplate() {
		return new ITemplate();
	}

	/**
	 * Create an instance of {@link IProject }
	 *
	 */
	public IProject createIProject() {
		return new IProject();
	}

	/**
	 * Create an instance of {@link ICloud }
	 *
	 */
	public ICloud createICloud() {
		return new ICloud();
	}
}
