vmware_url=https://vcenter.jpaas.com/sdk
vmware.infra.sslkeypath=D:/Backup/Swastika/Installers/BaaS/MASTER-HOME/Cognizant-JPaaS2-dev-1.0.jks
vmware.infra.sslpassword=Cognizant-JPaaS
vmware.infra.addressing=private
vmware.infra.machineimage=http://10.242.138.33:8280/services/MachineImageSoapServiceService
vmware.infra.virtualmachine=http://10.242.138.33:8280/services/VirtualMachineSoapServiceService
baashelp.portal.url=https://gto/JPaaS/BaaS/SitePages/BaasHome.aspx
vmware.infra.virtualmachine.ip.discovery.time=2

ec2.aws_url=http://ec2.amazonaws.com
ec2.sslkeypath=D:/Backup/Swastika/Installers/BaaS/MASTER-HOME/Cognizant-JPaaS2-dev-1.0.jks
ec2.sslpassword=Cognizant-JPaaS
ec2.addressing=private
ec2.machineimage=http://10.242.138.33:8280/services/MachineImageSoapServiceService
ec2.virtualmachine=http://10.242.138.33:8280/services/VirtualMachineSoapServiceService
ec2.virtualmachine.ip.discovery.time=2
ec2.pooled.time=180
