package com.cognizant.formit.util.db;

import com.cognizant.formit.model.RNode;
import com.cognizant.formit.model.RNodeFactory;
import com.cognizant.formit.util.db.DBHelper.*;
import com.cognizant.jpaas2.resource.VirtualMachineType;
import java.util.ArrayList;
import java.util.List;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.mockito.BDDMockito.*;
import org.mockito.Mock;

import static org.fest.assertions.api.Assertions.assertThat; // main one
import static org.fest.assertions.api.Assertions.atIndex; // for List assertion
import static org.fest.assertions.api.Assertions.entry;  // for Map assertion
import static org.fest.assertions.api.Assertions.extractProperty; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.fail; // use when making exception tests
import static org.fest.assertions.api.Assertions.failBecauseExceptionWasNotThrown; // idem
import static org.fest.assertions.api.Assertions.filter; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.offset; // for floating number assertion
import static org.fest.assertions.api.Assertions.anyOf; // use with Condition

public class DBHelperTest {

	@Test
	public void shoudlBeAbleToPushResourceDefinition() throws Exception {
		// TODO auto-generated by JUnit Helper.
		DBHelper target = DBHelper.newInstance(new IConnectionPoolInitializer() {
			private String dbUrl = "jdbc:mysql://10.227.125.41/rundeckdb";
			private String dbDriverClass = "com.mysql.jdbc.Driver";
			private String dbUid = "root";
			private String dbPwd = "mysql";
			private int dbInitialPoolSize = 10;
			private int dbMinPoolSize = 5;
			private int dbMaxPoolSize = 20;
			private int dbMaxIdleTime = 3600;

			public String dbUrl() {
				return dbUrl;
			}

			public String dbDriverClass() {
				return dbDriverClass;
			}

			public String dbUid() {
				return dbUid;
			}

			public String dbPwd() {
				return dbPwd;
			}

			public int dbMaxPoolSize() {
				return dbMaxPoolSize;
			}

			public int dbMinPoolSize() {
				return dbMinPoolSize;
			}

			public int dbInitialPoolSize() {
				return dbInitialPoolSize;
			}

			public int dbMaxIdleTime() {
				return dbMaxIdleTime;
			}
		});
//        // get the job  
//        VirtualMachineType machine = mock(VirtualMachineType.class);
//        List<RNode> nodes = new ArrayList<RNode>();
//        nodes = RNodeFactory.getDummyNodes();
//        // push resource definition
//        int numberOfInsertions = target.create(nodes);
//        assertThat(numberOfInsertions).isEqualTo(nodes.size());
//        // assert that we are succesful doing this
//        List<RNode> list = target.find(nodes.get(0).getName(), nodes.get(0).getHostname(), nodes.get(0).getUsername());
//        assertThat(list.get(0)).isEqualTo(nodes.get(0));
//        // clean up
//        int numberOfDeletions = target.delete(nodes.get(0).getName(), nodes.get(0).getHostname(), nodes.get(0).getUsername());
//        assertThat(numberOfDeletions).isEqualTo(1);
//        // shutdown the connection pool
		//target.cleanup();
		assertThat(target.find("13-1358419840543-6")).isNotEmpty();
	}
}
