data.interval.time=120
build.dataservice.endpoint=https://ip-172-19-2-132:8243/services/BaasBuildLogDetailsServiceGatewayService.BaasBuildLogDetailsServiceGatewayServiceHttpsSoap11Endpoint
datafederation.url=https://ip-172-19-2-132:8243/services/BaasBuildLogDetailsServiceGatewayService.BaasBuildLogDetailsServiceGatewayServiceHttpsSoap11Endpoint
build.dataservice.truststore.key=/EBS/Install/keys/Cognizant-JPaaS2-dev-1.0.jks
build.dataservice.trust.password=Cognizant-JPaaS
datafederation.truststore.key=/EBS/Install/keys/Cognizant-JPaaS2-dev-1.0.jks
datafederation.truststore.password=Cognizant-JPaaS

vmware_url=https://vcenter.jpaas.com/sdk
vmware.infra.sslkeypath=/EBS/Install/keys/Cognizant-JPaaS2-dev-1.0.jks
vmware.infra.sslpassword=Cognizant-JPaaS
vmware.infra.addressing=private
vmware.infra.machineimage=http://10.242.138.33:8280/services/MachineImageSoapServiceService
vmware.infra.virtualmachine=http://10.242.138.33:8280/services/VirtualMachineSoapServiceService
baashelp.portal.url=https://gto/JPaaS/BaaS/SitePages/BaasHome.aspx
vmware.infra.virtualmachine.ip.discovery.time=2
amazonUrl=http://ec2.amazonaws.com
allow.master.as.slave=false
