# BaaS - JPaaS provision DB integration parameters
# Credential to connect JPaaS DB for pushing build end data
#db.url=jdbc:mysql://10.236.159.91/provisiondb
#db.url=jdbc:mysql://10.227.125.3/provisiondb
#db.driver.class=com.mysql.jdbc.Driver
db.uid=root
db.pwd=mysql
db.initialPoolSize=10
db.minPoolSize=5
db.maxPoolSize=20
# In seconds
db.maxIdleTime=3600
# Schema
db.schema=provisiondb
# Build end data capturing table
db.table=baas_build_log
# BaaS - ACLService integration parameters
# Credential to connect JPaaS ACLService for ensuring RBAC features of BaaS
#acl.service.endpoint=http://10.236.159.94:8080/JpaasBuildService/services/JpaasBuildServiceImpl.JpaasBuildServiceImplHttpSoap11Endpoint/
#acl.service.endpoint=http://10.227.88.145:8280/services/RBACService.RBACServiceHttpEndpoint
acl.service.endpoint=https://ip-172-19-2-132:8243/services/RBACService.RBACServiceHttpEndpoint?wsdl
# BaaS - RTC Q integration parameters
# Credential to connect JPaaS RTC -Integration service for querying RTC Q
# In case BaaS runs in -DMODE=RTC, following property should indicate the RTC integration service's endpoint
#rtc.service.endpoint=http://localhost:9090/rtcintegration-server/RTCServlet
#datafederation.url=http://10.227.88.145:8280/services/BaasBuildLogDetailsServiceGatewayService.BaasBuildLogDetailsServiceGatewayServiceHttpsSoap11Endpoint
#build.dataservice.endpoint=http://10.227.88.145:8280/services/BaasBuildLogDetailsServiceGatewayService.BaasBuildLogDetailsServiceGatewayServiceHttpsSoap11Endpoint

build.dataservice.endpoint=http://ip-172-19-2-132:8280/services/BaasBuildLogDetailsServiceGatewayService.BaasBuildLogDetailsServiceGatewayServiceHttpsSoap11Endpoint
datafederation.url=http://ip-172-19-2-132:8280/services/BaasBuildLogDetailsServiceGatewayService.BaasBuildLogDetailsServiceGatewayServiceHttpsSoap11Endpoint
build.dataservice.truststore.key=/EBS/Install/keys/Cognizant-JPaaS2-dev-1.0.jks
build.dataservice.trust.password=Cognizant-JPaaS
datafederation.truststore.key=/EBS/Install/keys/Cognizant-JPaaS2-dev-1.0.jks
datafederation.truststore.password=Cognizant-JPaaS
ec2.eucalyptus_url=http://10.227.125.3:8773/services/Eucalyptus
ec2.aws_url=http://ec2.amazonaws.com
ec2.vmware_url=https://10.242.196.192/sdk
ec2.sslkeypath=/EBS/Install/keys/Cognizant-JPaaS2-dev-1.0.jks
ec2.sslpassword=Cognizant-JPaaS
ec2.addressing=private
ec2.machineimage=https\://ip-172-19-2-132\:8243/services/MachineImageSoapServiceService
ec2.virtualmachine=https\://ip-172-19-2-132\:8243/services/VirtualMachineSoapServiceService
baashelp.portal.url=https://gto/JPaaS/BaaS/SitePages/BaasHome.aspx
eucalyptus.resource=https://ip-172-19-2-132:8243/services/EucalyptusResourceManagementService.EucalyptusResourceManagementServiceHttpsEndpoint
ec2.virtualmachine.ip.discovery.time=10