package com.cognizant.formit.util.file;

import com.cognizant.formit.AbstractTest;
import com.cognizant.formit.util.file.FileHelper.*;
import java.io.FileInputStream;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.mockito.BDDMockito.*;

import static org.fest.assertions.api.Assertions.assertThat; // main one
import static org.fest.assertions.api.Assertions.atIndex; // for List assertion
import static org.fest.assertions.api.Assertions.entry;  // for Map assertion
import static org.fest.assertions.api.Assertions.extractProperty; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.fail; // use when making exception tests
import static org.fest.assertions.api.Assertions.failBecauseExceptionWasNotThrown; // idem
import static org.fest.assertions.api.Assertions.filter; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.offset; // for floating number assertion
import static org.fest.assertions.api.Assertions.anyOf; // use with Condition

public class FileUtilTest extends AbstractTest {

//	@Test
//	public void readXMLAsFileInputStream_A$String() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		// given
//		// given
//		// defines dependency between container / executables        
//		// e.g. : given(mocked.called()).willReturn(1);
//		// when
//		FileInputStream actual = FileHelper.readXMLAsFileInputStream(super.getDeployer().getXmlFilePath());
//		// then
//		// e.g. : verify(mocked).called();
//		assertThat(actual).isInstanceOf(FileInputStream.class);
//	}
}
