db.url=jdbc:mysql://10.236.159.91/provisiondb
db.driver.class=com.mysql.jdbc.Driver
db.uid=root
db.pwd=mysql
db.schema=provisiondb
db.table=baas_build_log
datafederation.url=http://10.227.88.145:8280/services/BaasBuildLogDetailsServiceGatewayService.BaasBuildLogDetailsServiceGatewayServiceHttpsSoap11Endpoint