package com.cognizant.formit.util.rundeck;

import com.cognizant.formit.main.SequentialExecutor;
import com.cognizant.formit.util.file.FileHelper;
import com.cognizant.formit.util.parser.XmlParser;
import java.io.IOException;
import java.io.InputStream;
import javax.xml.parsers.ParserConfigurationException;
import org.rundeck.api.FileType;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

import com.cognizant.formit.util.rundeck.RundeckHelper.*;
import java.io.File;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.mockito.BDDMockito.*;

import java.util.List;
import org.apache.tools.ant.Project;
import org.apache.tools.ant.Task;
import org.rundeck.api.OptionsBuilder;
import org.rundeck.api.RundeckClient;
import org.rundeck.api.domain.RundeckExecution;
import org.rundeck.api.domain.RundeckJob;
import org.rundeck.api.domain.RundeckProject;

import static org.fest.assertions.api.Assertions.assertThat; // main one
import static org.fest.assertions.api.Assertions.atIndex; // for List assertion
import static org.fest.assertions.api.Assertions.entry;  // for Map assertion
import static org.fest.assertions.api.Assertions.extractProperty; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.fail; // use when making exception tests
import static org.fest.assertions.api.Assertions.failBecauseExceptionWasNotThrown; // idem
import static org.fest.assertions.api.Assertions.filter; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.offset; // for floating number assertion
import static org.fest.assertions.api.Assertions.anyOf; // use with Condition

public class RundeckHelperTest {
//    @Test
//    public void testIfParameterizedConnectivityIsPossible() throws Exception {
//        // TODO auto-generated by JUnit Helper.
//        RundeckHelper target = newRundeckHelper();
//        // given
//        IRundeckConnectionInitializer connectionInitializer = new IRundeckConnectionInitializer() {
//            @Override
//            public String serverEndpoint() {
//                return "http://10.227.125.52:4440";
//            }
//
//            @Override
//            public String uid() {
//                return "admin";
//            }
//
//            @Override
//            public String pwd() {
//                return "admin";
//            }
//        };
//        // e.g. : given(mocked.called()).willReturn(1);
//        // when
//        RundeckClient actual = target.connect(connectionInitializer);
//        // then
//        // e.g. : verify(mocked).called();
//        assertThat(actual).isNotNull();
//    }
//
//    @Test
//    public void testIfWeCanConnectByDefault() throws Exception {
//        // TODO auto-generated by JUnit Helper.
//        RundeckHelper target = RundeckHelper.getInstance();
//        // given
//        // e.g. : given(mocked.called()).willReturn(1);
//        // when
//        RundeckClient actual = target.connect();
//        // then
//        // e.g. : verify(mocked).called();
//        assertThat(actual).isNotNull();
//    }
//
////    @Test
////    public void findAJob() throws Exception {
////        // TODO auto-generated by JUnit Helper.
////        RundeckHelper target = null;
////        // given
////        String jobId = null;
////        // e.g. : given(mocked.called()).willReturn(1);
////        // when
////        RundeckJob actual = target.findJob(jobId);
////        // then
////        // e.g. : verify(mocked).called();
////        RundeckJob expected = null;
////        assertThat(actual, is(equalTo(expected)));
////    }
////
//    @Test
//    public void testIfJobHasBeenReceivedInFormOfAnInputstream() throws Exception {
//        // TODO auto-generated by JUnit Helper.
//        // TODO auto-generated by JUnit Helper.
//        RundeckHelper target = RundeckHelper.getInstance();
//        // given
//        RundeckClient client = target.connect();
//        // given
//        String jobId = "ecdd040a-4828-11e2-b079-f23c91aec05e";
//        // e.g. : given(mocked.called()).willReturn(1);
//        // when
//        InputStream actual = target.getJobFile(jobId);
//        // then
//        // e.g. : verify(mocked).called();        
//        assertThat(actual).isNotNull();
//    }
//
//    @Test
//    public void testIfJobOptionsHasBeenDiscovered() throws Exception {
//        // TODO auto-generated by JUnit Helper.
//        // TODO auto-generated by JUnit Helper.
//        RundeckHelper target = RundeckHelper.getInstance();
//        // given
//        RundeckClient client = target.connect();
//        // given
//        String jobId = "ecdd040a-4828-11e2-b079-f23c91aec05e";
//        // e.g. : given(mocked.called()).willReturn(1);
//        // when
//        RundeckJob rundeckJob = target.findJob(jobId);
//        // then
//        // e.g. : verify(mocked).called();
//        assertThat(rundeckJob).isNotNull();
//        assertThat(rundeckJob.getOptions()).hasSize(10);
//    }
//
//    @Test
//    public void testIfJobWithoutOptionsCanBeManagedAsWell() throws Exception {
//        // TODO auto-generated by JUnit Helper.
//        // TODO auto-generated by JUnit Helper.
//        RundeckHelper target = RundeckHelper.getInstance();
//        // given
//        RundeckClient client = target.connect();
//        // given
//        String jobId = "df65c15f-2ea4-4e7a-8b95-61bcc2de0add";
//        // e.g. : given(mocked.called()).willReturn(1);
//        // when
//        RundeckJob rundeckJob = target.findJob(jobId);
//        // then
//        // e.g. : verify(mocked).called();
//        assertThat(rundeckJob).isNotNull();
//        assertThat(rundeckJob.getOptions()).isNull();
//    }
}
