package com.cognizant.formit.model;

import com.cognizant.formit.AbstractTest;
import static org.fest.assertions.api.Assertions.assertThat; // main one
import static org.fest.assertions.api.Assertions.atIndex; // for List assertion
import static org.fest.assertions.api.Assertions.entry;  // for Map assertion
import static org.fest.assertions.api.Assertions.extractProperty; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.fail; // use when making exception tests
import static org.fest.assertions.api.Assertions.failBecauseExceptionWasNotThrown; // idem
import static org.fest.assertions.api.Assertions.filter; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.offset; // for floating number assertion
import static org.fest.assertions.api.Assertions.anyOf; // use with Condition

import com.cognizant.formit.model.DeploymentConfigDecorator.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import com.cognizant.formit.entity.infrastructureContext.Context;
import com.cognizant.formit.main.Executor;
import com.cognizant.formit.main.SequentialExecutor;
import com.cognizant.formit.util.parser.XmlParser;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import org.w3c.dom.Document;

public class DeploymentConfigDecoratorTest extends AbstractTest {

//	@Test
//	public void shouldDecorateBlueprintWithProfileData() throws Exception {
//
//
//		// given
//		// Deployment starts with grabbing an instance of SequentialExecutor
//		Executor deployer = super.getDeployer();
//		DeploymentConfigDecorator target = DeploymentConfigDecorator.newInstance(DeploymentProfileFactory.ProfileSourceType.PROPERTY_FILE, deployer.getProfileFilePath());
//		assertThat(target.getDeploymentProfile().get()).isNotEmpty().hasSize(21);
//		// decorate xml with the properties received thus
//		// TODO auto-generated by JUnit Helper.            		
//		XmlParser parser = XmlParser.newInstance();
//		// given
//		target.registerPlusDecorateDeploymentConfig(deployer.getXmlFilePath(), deployer.getXsdFilePath());
//
//		// binder input	
//		IDeploymentConfig deploymentConfig = target.unmarshalDecoratedConfig(deployer.getSchemaPkg(), deployer.getObjFactory());
//		assertThat(((Context) deploymentConfig).getCloud().getName()).isEqualTo("eucalyptus");
//	}
//
//	@Test
//	public void shouldFailInDecoratingBlueprintWithProfileData() throws Exception {
//		// TODO : Create a full negative test
//	}
}
