package com.cognizant.formit.util.parser;

import com.cognizant.formit.AbstractTest;
import com.cognizant.formit.util.parser.XmlBinder.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.mockito.BDDMockito.*;

import com.cognizant.formit.entity.infrastructureContext.BaseObjectFactory;
import com.cognizant.formit.model.IDeploymentConfig;
import com.cognizant.formit.entity.infrastructureContext.Context;
import com.cognizant.formit.util.file.FileHelper;
import static javax.xml.XMLConstants.W3C_XML_SCHEMA_NS_URI;
import java.io.File;
import java.io.FileInputStream;
import java.util.Map;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.ValidationEvent;
import javax.xml.bind.ValidationEventHandler;
import javax.xml.bind.ValidationEventLocator;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import org.apache.log4j.Logger;
import org.xml.sax.SAXException;

public class XmlBinderTest extends AbstractTest {
//
//	@Test
//	public void type() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		assertThat(XmlBinder.class, notNullValue());
//	}
//
//	@Test
//	public void instantiation() throws Exception {
//
//		XmlBinder target = XmlBinder.newInstance(super.getDeployer().getSchemaPkg(), super.getDeployer().getObjFactory());
//		assertThat(target, notNullValue());
//	}
//
//	@Test
//	public void shouldBindValidXml() throws Exception {
//		// TODO auto-generated by JUnit Helper.            
//		// given
//
//		XmlBinder target = XmlBinder.newInstance(super.getDeployer().getSchemaPkg(), super.getDeployer().getObjFactory());
//
//		target.registerValidator(super.getDeployer().getXsdFilePath());
//		// e.g. : given(mocked.called()).willReturn(1);
//		// when
//		IDeploymentConfig actual = target.parse(super.getDeployer().getXmlFilePath());
//		Context context = (Context) actual;
//		// then
//		// e.g. : verify(mocked).called();
//		assertThat(context.getCloud(), notNullValue());
//	}
}
