package com.cognizant.formit.util.parser;

import com.cognizant.formit.AbstractTest;
import com.cognizant.formit.util.parser.XmlParser.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.ParseException;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.FactoryConfigurationError;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Source;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;
import org.apache.log4j.Logger;
import org.w3c.dom.Document;
import org.w3c.dom.DocumentType;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;


import static org.fest.assertions.api.Assertions.assertThat; // main one
import static org.fest.assertions.api.Assertions.atIndex; // for List assertion
import static org.fest.assertions.api.Assertions.entry;  // for Map assertion
import static org.fest.assertions.api.Assertions.extractProperty; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.fail; // use when making exception tests
import static org.fest.assertions.api.Assertions.failBecauseExceptionWasNotThrown; // idem
import static org.fest.assertions.api.Assertions.filter; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.offset; // for floating number assertion
import static org.fest.assertions.api.Assertions.anyOf; // use with Condition
import org.xml.sax.SAXParseException;

public class XmlParserTest extends AbstractTest {

//	@Test
//	public void shouldParseValidXml() throws Exception {
//		// TODO auto-generated by JUnit Helper.            		
//		XmlParser target = XmlParser.newInstance();
//		// given
//		// given
//		// defines dependency between container / executables        
//		target.registerValidator(super.getDeployer().getXsdFilePath());
//		// e.g. : given(mocked.called()).willReturn(1);
//		// when
//		Document actual = target.parse(super.getDeployer().getXmlFilePath());
//		// then
//		// e.g. : verify(mocked).called();
//		assertThat(actual).isNotNull();
//	}
//
//	@Test
//	public void shouldFailInParsingInvalidXml() throws Exception {
////        // TODO auto-generated by JUnit Helper.            		
////        XmlParser target = XmlParser.newInstance();
////        // given
////        // given
////        // defines dependency between container / executables
////        String blueprintConfigFilePath = "src/main/resources/xml/Blueprint_valid.xml";
////        // defines valid resources
////        String xmlFilePath = "src/main/resources/xml/InfrastructureContext_invalid.xml";
////        // defines xsd for validating resource definitions to be used by blueprint
////        String xsdFilePath = "src/main/resources/xsd/InfrastructureContext.xsd";
////        // defines deployment profile
////        String profileFilePath = "src/main/resources/properties/EnvironmentProfile_valid.properties";
////
////        // binder input
////        String schemaPkg = "com.cognizant.formit.entity.environmentprofile";
////        String objFactory = "com.cognizant.formit.entity.environmentprofile.ObjectFactory";
////        target.registerValidator(xsdFilePath);
////        // e.g. : given(mocked.called()).willReturn(1);
////        // when
////        try {
////            Document actual = target.parse(xmlFilePath);
////        } catch (Exception e) {
////            assertThat(e).isInstanceOf(SAXParseException.class);
////        }
////        // then
////        // e.g. : verify(mocked).called();
//	}
}
