// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cognizant.jpaas2.todo;

import com.cognizant.jpaas2.todo.TODO;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TODO_Roo_Configurable {
    
    declare @type: TODO: @Configurable;
    
}
