package com.cognizant.formit.main;

import com.cognizant.formit.main.ExecutorFactory.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.mockito.BDDMockito.*;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.apache.log4j.Logger;

import static org.fest.assertions.api.Assertions.assertThat; // main one
import static org.fest.assertions.api.Assertions.atIndex; // for List assertion
import static org.fest.assertions.api.Assertions.entry;  // for Map assertion
import static org.fest.assertions.api.Assertions.extractProperty; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.fail; // use when making exception tests
import static org.fest.assertions.api.Assertions.failBecauseExceptionWasNotThrown; // idem
import static org.fest.assertions.api.Assertions.filter; // for Iterable/Array assertion
import static org.fest.assertions.api.Assertions.offset; // for floating number assertion
import static org.fest.assertions.api.Assertions.anyOf; // use with Condition
public class ExecutorFactoryTest {
//
//	@Test
//	public void testIfCanSpawnInstance() throws Exception {
//		// TODO auto-generated by JUnit Helper.
//		// given
//		// e.g. : given(mocked.called()).willReturn(1);
//		// when
//		Executor actual = ExecutorFactory.newExecutor(ExecutorFactory.ExecutorType.SEQUENTIAL, UUID.randomUUID().toString());
//		// then
//		// e.g. : verify(mocked).called();		
//		assertThat(actual.getUniqueRunId()).isNotNull();
//
//		Executor findThisFromMap = ExecutorFactory.getExecutor(actual.getUniqueRunId());
//
//		assertThat(findThisFromMap).isEqualTo(actual);
//	}
}
