#Updated at Fri Jan 25 14:18:47 IST 2013
#Fri Jan 25 14:18:47 IST 2013
database.driverClassName=com.mysql.jdbc.Driver
database.url=jdbc\:mysql\://10.227.125.41\:3306/todorepo
database.username=root
database.password=mysql
